steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [ './get_images.sh', 'import' ]
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'LOCATION=$LOCATION'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/monitoring/tiller', '.' ]
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/monitoring/tiller:latest'
