---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: {{ .Values.global.namespace }}
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: front-end
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    #nodePort: 30001
  selector:
    name: front-end
