---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: {{ .Values.global.namespace }}
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: orders
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ .Values.orders.containerPort }}
  selector:
    name: orders
