---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: {{ .Values.global.namespace }}
  labels:
    name: payment
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ .Values.payment.containerPort }}
  selector:
    name: payment
