---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  namespace: {{ .Values.global.namespace }}
  labels:
    name: queue-master
  annotations:
    prometheus.io/path: "/prometheus"
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: queue-master
